rog/urls.py
from django.conf.urls import patterns, include, url, handler404, handler500, handler403, handler400
from django.contrib import admin, auth
from rogging import views
import settings
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'rog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin', include(admin.site.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^passwordreset$', views.passwordReset, name='passwordReset'),
	# part past "passwordresetconfirm/" from https://docs.djangoproject.com/en/1.9/topics/auth/default/#using-the-views
	url(r'^passwordresetconfirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})$', views.passwordResetConfirm, name='password_reset_confirm'),
	url(r'^passwordresetcomplete$', views.passwordResetComplete, name='password_reset_complete'),
    url(r'^', include('rogging.urls', namespace="rogging")),
)

handler404 = 'rogging.views.rogger404'
handler500 = 'rogging.views.rogger500'
handler403 = 'rogging.views.rogger403'
handler400 = 'rogging.views.rogger400'

rogging/urls.py
from django.conf.urls import url

import views
from django.contrib import auth

urlpatterns = [
	url(r'^login$', views.loginUser, name='loginUser'),
	url(r'^createaccount$', views.createAccount, name='createAccount'),
	url(r'^accountcreated$', views.accountCreated, name='accountCreated'),
	url(r'^logoutsuccess$', views.logoutSuccess, name='logoutSuccess'),
	url(r'^logger$', views.roggerLogger, name='roggerLogger'),
	url(r'^resources$', views.resources, name='resources'),
	url(r'^importer$', views.importer, name='importer'),
	url(r'^settings$', views.settings, name='settings'),
	url(r'^settings/changepassword$', views.changePassword, name='changePassword'),
	url(r'^settings/export$', views.export, name='export'),
	url(r'^lostusernames$', views.lostUsername, name='lostUsername'),
	url(r'^search$', views.search, name='search'),
	url(r'^accountsetup$', views.accountSetup, name='accountSetup'),
	url(r'^(?P<username>([0-9]|[a-z]|[A-Z]|_)+)$', views.show, name='show'),
	url(r'^runs/(?P<run>[0-9]+)$', views.accessRun, name='accessRun'),
	url(r'^(?P<username>([0-9]|[a-z]|[A-Z]|_)+)/weekof(?P<weekof>([0-9][0-9][0-9][0-9][0-1][0-9][0-3][0-9])).pdf$', views.getWeekPDF, name='getPDF'),
	url(r'^$', views.homepage, name='homepage')
]

rogging/models.py
from django.db import models
import datetime
from urlparse import urlparse, parse_qs
from time import time, clock
from views import awsImageRetrieval, getAWSInfo
from django.contrib.auth.models import User
from django.conf import settings
from django.http import Http404, HttpResponseForbidden, HttpResponseNotFound
from django.template.context import RequestContext
from django.template import loader
# Create your models here.

awsInfo = getAWSInfo()

class RoggeeLog(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, default=None)
	hasProfilePicture = models.BooleanField(default=False)
	hasBannerPicture = models.BooleanField(default=False)
	name = models.CharField(max_length=100, null=True, default=None)
	searchUsername = models.NullBooleanField(default=None)
	searchName = models.NullBooleanField(default=None)
	loadUserPageFirst = models.BooleanField(default=False)
	pseudoPrivate = models.BooleanField(default=False)
	private = models.BooleanField(default=False)
	
	def getThumbnail(self):
		global awsInfo
		return awsImageRetrieval(self.user, 'thumbnail', awsInfo)
	
	def getProfilePic(self):
		global awsInfo
		return awsImageRetrieval(self.user, 'profile', awsInfo)
	
	def getBannerPic(self):
		global awsInfo
		return awsImageRetrieval(self.user, 'banner', awsInfo)
	
	def showSetup(self):
		return (self.searchUsername == None
				or
				self.searchName == None
				or
				(self.name == None))
	
	def isBlockedByLog(self, blockerLog):
		return Block.objects.filter(blockedLog=self, blockerLog=blockerLog).exists()
	
	def isBlockedByUser(self, blocker):
		if blocker.is_authenticated():
			return Block.objects.filter(blockedLog=self, blockerLog=blocker.roggeelog).exists()
		else:
			return False
	
	def shouldRenderFor(self, requester):
		permissionToRender = True
		if (self.private or self.pseudoPrivate) and not requester.is_authenticated():
			permissionToRender = False
		if self.private and requester.is_authenticated() and self != requester.roggeelog:
			permissionToRender = False
		elif self.pseudoPrivate and requester.is_authenticated() and self != requester.roggeelog:
			if not Follow.objects.filter(followedLog=self, followerLog=requester.roggeelog, approved=True).exists():
				permissionToRender = False
		
		return permissionToRender
		
	def renderLevelForUser(self, user):
		if not user.is_authenticated():
			if not (self.private or self.pseudoPrivate):
				return 1
			else:
				if self.private:
					return -1
				else:
					return 0
		elif self != user.roggeelog and (self.private or user.roggeelog.isBlockedByLog(self)):
			return -1
		elif self.pseudoPrivate:
			if not (Follow.objects.filter(followedLog=self, followerLog=user.roggeelog, approved=True).exists() or self == user.roggeelog):
				return 0
		return 1
		
	def renderLevelFor(self, requestingLog):
		if requestingLog == None and not (self.private or self.pseudoPrivate):
			return 1
		if self != requestingLog and (self.private or requestingLog.isBlockedByLog(self)):
			return -1
		elif self.pseudoPrivate:
			if not (Follow.objects.filter(followedLog=self, followerLog=requestingLog, approved=True).exists() or self == requestingLog):
				return 0
		return 1
	
	def renderProperResponse(self, f, request):
		renderLevel = self.renderLevelForUser(request.user)
		if renderLevel == 1:
			return f()
		elif renderLevel == 0:
			return HttpResponseForbidden(loader.render_to_string('rogging/403.html', context=RequestContext(request)))
		else:
			return HttpResponseNotFound(loader.render_to_string('rogging/404.html', context=RequestContext(request)))
		
	def __str__(self):
		return self.user.username
		
class Shoe(models.Model):
	name = models.CharField(max_length=200)
	relatedLog = models.ForeignKey(RoggeeLog, related_name='shoe_relatedlog', null=True, default=None)
	
class LogEntry(models.Model):
	title = models.CharField(max_length=500)
	date = models.DateField()
	relatedLog = models.ForeignKey(RoggeeLog, related_name="logentry_relatedlog", null=True, default=None)
	entry = models.TextField()
	distance = models.FloatField(default=0.0)
	dateTimeCreated = models.DateTimeField(default=datetime.datetime.now())
	hoursRan = models.FloatField(default=0.0, null=True)
	minutesRan = models.FloatField(default=0.0, null=True)
	secondsRan = models.FloatField(default=0.0, null=True)
	shoe = models.ForeignKey(Shoe, related_name="logentry_shoe", default=None, null=True)
	kind = models.CharField(max_length=200, default="Run") #from merv
	
	# Merv/Import stuff
	mervSubtype = models.CharField(max_length=200, default=None, null=True) #from merv
	mervAddendumToSummary = models.CharField(max_length=500, null=True) #from merv
	mervRestHeartrate = models.FloatField(default=None, null=True) #from merv
	mervDistanceUnit = models.CharField(max_length=200, default="miles")
	mervPace = models.CharField(max_length=200, default=None, null=True)
	mervPaceUnit = models.CharField(max_length=200, default="/mi")
	imported = models.BooleanField(default=False)


	def __unicode__(self):
		return self.title
	
	def displayTitle(self):
		if self.title == "":
			return self.kind + ": " + str(self.distance) + " " + (self.mervAddendumToSummary if self.mervAddendumToSummary != None else "")
		else:
			return self.title + " " + (self.mervAddendumToSummary if self.mervAddendumToSummary != None else "")
	
	def distanceInDesiredUnits(self):
		# FOR NOW, THIS CONVERTS TO MILES
		if self.mervDistanceUnit == "miles" or self.mervDistanceUnit == "mi":
			return self.distance
		elif self.mervDistanceUnit == "km":
			return (self.distance * (1.0/1.609))
		else:
			return (self.distance * (1.0/1609.0))
			
	def getNumberOfComments(self):
		return Comment.objects.filter(respectiveRun=self).count()
		
	def timeRanString(self):
		if self.hoursRan != None and self.minutesRan != None and self.secondsRan != None:
			hoursFormatted = str(int(self.hoursRan)) if self.hoursRan >= 10 else "0" + str(int(self.hoursRan))
			minutesFormatted = str(int(self.minutesRan)) if self.minutesRan >= 10 else "0" + str(int(self.minutesRan))
			secondsFormatted = str(self.secondsRan) if self.secondsRan >= 10 else "0" + str(self.secondsRan)
			return hoursFormatted + ":" + minutesFormatted + ":" + secondsFormatted
		return ""
	
	def paceString(self):
		if self.hoursRan != None and self.minutesRan != None and self.secondsRan != None and self.distanceInDesiredUnits() > 0.0:
			from views import paceCalculator
			return paceCalculator(self.hoursRan, self.minutesRan, self.secondsRan, self.distanceInDesiredUnits())
		return ""
		
		

class Comment(models.Model):
	dateTimeMade = models.DateTimeField(default=datetime.datetime.now())
	respectiveRun = models.ForeignKey(LogEntry, related_name='comment_respectiverun')
	comment = models.TextField()
	commenterLog = models.ForeignKey(RoggeeLog, related_name='comment_commenterlog', null=True, default=None)
	
	def __str__(self):
		return "Comment by " + self.commenterLog.user.username
	
class Follow(models.Model):
	followedLog = models.ForeignKey(RoggeeLog, related_name='follow_followedlog', null=True, default=None)
	followerLog = models.ForeignKey(RoggeeLog, related_name='follow_followerlog', null=True, default=None)
	approved = models.BooleanField(default=False)
	
class Block(models.Model):
	blockedLog = models.ForeignKey(RoggeeLog, related_name='block_blockedlog')
	blockerLog = models.ForeignKey(RoggeeLog, related_name='block_blockerlog')
	
class Tag(models.Model):
	entry = models.ForeignKey(LogEntry, related_name='tag_entry', null=True)
	comment = models.ForeignKey(Comment, related_name='tag_comment', null=True)
	taggedLog = models.ForeignKey(RoggeeLog, related_name='tag_taggedlog', null=True, default=None)
	
class Metric(models.Model):
	relatedLog = models.ForeignKey(RoggeeLog, related_name='metric_relatedlog', null=True, default=None)
	name = models.CharField(max_length=200)
	distance = models.FloatField(default=0.0)
	
class PictureCacheURL(models.Model):
	relatedLog = models.ForeignKey(RoggeeLog, related_name='picturecacheurl_relatedlog', null=True, default=None)
	url = models.CharField(max_length=1000)
	forResource = models.CharField(max_length=100)
	
	def stillValid(self):
		parsedURL = urlparse(self.url)
		parsedQuery = parse_qs(parsedURL.query)
		validUntil = parsedQuery['Expires'][0]
		buffer = 20 #in seconds
		if (time() + 20) < int(validUntil):
			return True
		else:
			return False
	
	def __str__(self):
		parsedURL = urlparse(self.url)
		parsedQuery = parse_qs(parsedURL.query)
		validUntil = parsedQuery['Expires'][0]
		return self.relatedLog.user.username + ", expires " + str(datetime.datetime.utcfromtimestamp(float(validUntil))) + " UTC"

rogging/templates/rogging/changepassword.html
{% extends "rogging/starter.html" %}

{% block content %}
<link href="{{ STATIC_URL }}changepassword.css" rel="stylesheet">
{% block error %}{% endblock %}
<form action="{% url 'rogging:changePassword' %}" method="post" class="form-signin">
	<h2 class="form-signin-heading">Change Password</h2>
	{% csrf_token %}
	<input id="id_currentPassword" name="currentPassword" type="password" class="form-control" placeholder="Current password" required autofocus/>
	<input id="id_newPassword" name="newPassword" type="password" class="form-control" placeholder="New password" required/>
	<input id="id_confirmNewPassword" name="confirmNewPassword" type="password" class="form-control" placeholder="Re-enter new password" required/>
	<button class="btn btn-lg btn-primary btn-block" type="submit" id="changepasswordbutton">
		<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
	</button>
</form>
{% endblock %}

rogging/templates/rogging/changepasswordnotloggedin.html
{% extends "rogging/starter.html" %}

{% block content %}
You need to be logged in to use this feature.
{% endblock %}

rogging/templates/rogging/createaccountalreadyused.html
{% extends "rogging/createaccount.html" %}

{% block error %}
The username that you desire is already being used; Please enter another.
{% endblock %}

rogging/templates/rogging/logger.html
{% extends "rogging/starter.html" %}
{% load formattingfilters %}
{% block content %}
{% block error %}{% endblock %}
<style>
	{% include "rogging/loggercss.html" %}
	/*#loggerwell * { animation-name:loggerwellanimation; animation-duration:1s; }*/
</style>
<div id="loggerDiv" class="fadeInBottom">
	<form action="{% url 'rogging:roggerLogger' %}" method="post" id="loggerForm">
		{% csrf_token %}
		{% include "rogging/prepace.html" %}
		{% include "rogging/predelete.html" %}
		<button class="btn btn-lg btn-primary btn-block" type="button" id="submitEntryButton" onclick="submitEntry()"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></button>
	</form>
</div>

<!--CACHING VERSIONING IDEA FROM http://stackoverflow.com/questions/17777429/django-static-files-are-not-updated-->
<script src="{{ STATIC_URL}}logparsing3v1.0.js"></script>
<script src="{{ STATIC_URL}}tinymce/js/tinymce/tinymce.min.js"></script>
<script>
{% include "rogging/loggerjs.html" %}

/////////////////////// POST-LOAD //////////////////////////
{% include "rogging/loggerjspostload.html" %}
function adjustButton() {
	if ($(window).width() < 768) {
		$("#submitEntryButton").css("width", "100%").css("margin", "");
	} else {
		$("#submitEntryButton").css("width", "50%").css("margin", "auto");
	}
}
window.addEventListener("resize", adjustButton);
adjustButton();
{% if date != "" %}
$("#id_date")[0].value = "{{ date }}";
{% else %}
var currentDate = new Date();
var day = currentDate.getDate() < 10 ? "0" + currentDate.getDate() : currentDate.getDate();
var month = currentDate.getMonth()+1 < 10 ? "0" + (currentDate.getMonth() + 1) : (currentDate.getMonth() + 1);
$("#id_date")[0].value = currentDate.getFullYear() + "-" + month + "-" + day;
{% endif %}

window.addEventListener("beforeunload", animateUnload);
function animateUnload() {
	var loggerDiv = $("#loggerDiv");
	loggerDiv.removeClass("fadeInBottom");
	loggerDiv.addClass("fadeOutBottom");
}

var logContent = "{{ form.data.entry|newlinesToSlashNs }}";
tinymce.init({ selector: "#tinyMCEEntry",
				inline: true,
				content_css: "{{ STATIC_URL }}content.inline.min.css",
				plugins: "paste",
				toolbar: false,
				menubar: false,
				// IGNORING CERTAIN ELEMENTS IDEA FROM http://stackoverflow.com/questions/22184625/tinymce-ctrl-v-paste-as-plain-text-must-remove-chosen-foreign-elements
				valid_elements: "p, strong, a, span",
				paste_as_text: true,
				setup: function(ed) {
							ed.on('init', function() {
											copyToPreview(logContent);
											ed.on('keyup', function() {
													copyToPreview("");
											});				
							});
						}
				});
</script>
{% endblock %}

rogging/templates/rogging/loggereditsave.html
{% extends "rogging/loggeredit.html" %}

{% block error %}
<style>
	#savedNotice { font-family:"Perpetua", sans-serif; font-weight:lighter }
</style>
<div class="alert alert-success" role="alert" id="savedNotice">The log entry was saved</div>
{% endblock %}

rogging/templates/rogging/loggerjs.html
function formatString(theString, units) {
	positionData = logParsingAutomaton(theString, units)[1]
	
	offsetOfAddedHTMLTags = 0
	var i = 0
	while (i < positionData.length) {
		var start = positionData[i][0] + offsetOfAddedHTMLTags
		var end = positionData[i][1] + offsetOfAddedHTMLTags
		
		theString = theString.slice(0, start) + "<strong>" + theString.slice(start, end) + "</strong>" + theString.slice(end);
		offsetOfAddedHTMLTags += 17;
		
		i += 1;
	}
	
	return theString;
}

function replaceNewlinesWithParas(theString) {
	if (theString.length != 0) {
		theString = "<p>" + theString.replace(/\n/g, "<br data-mce-bogus=\"1\"></p><p>") + "<br data-mce-bogus=\"1\"></p>"
	}
	return theString
}

function removeHTMLTags(theString) {
	// IGNORING THE SPANS FROM http://stackoverflow.com/questions/6449131/javascript-regular-expression-to-not-match-a-word
	// REMOVING HTML TAGS FROM http://stackoverflow.com/questions/822452/strip-html-from-text-javascript
	return theString.replace(/<\/p>[\s]*<p>/g, "\n").replace(/<(?!(span id="lastCursor">|\/span>))[^>]*>/g, "");
}

function removeHTML(theString) {
	// IGNORING THE SPANS FROM http://stackoverflow.com/questions/6449131/javascript-regular-expression-to-not-match-a-word
	// REMOVING HTML TAGS FROM http://stackoverflow.com/questions/822452/strip-html-from-text-javascript
	return theString.replace(/<\/p>[\s]*<p>/g, "\n").replace(/<(?!(span id="lastCursor">|\/span>))[^>]*>/g, "").replace(/&nbsp;/g, " ");
}

function submitEntry() {
	$("#id_entry")[0].value = removeHTML(tinymce.get("tinyMCEEntry").getContent({ format: 'raw' }));
	$("#loggerForm")[0].submit();
}

function copyToPreview(stringToCopy) {
	var mceInstance = tinymce.get("tinyMCEEntry");
	var units = {{ units|safe }};
	var unitLengths = {{ unitConversions|safe }};
	var escapedEntry = "";
	if (stringToCopy == "") {
		// CURSOR SAVING FROM http://stackoverflow.com/questions/1253303/whats-the-best-way-to-set-cursor-caret-position
		if (mceInstance.selection.isCollapsed()) {
			tinymce.get("tinyMCEEntry").selection.setContent("<span id=\"lastCursor\"></span>");
		}
		escapedEntry = removeHTMLTags(tinymce.get("tinyMCEEntry").getContent({ format: 'raw' }));
	} else {
		escapedEntry = stringToCopy;
	}
	var automatonRunthrough = logParsingAutomaton(escapedEntry, units);
	var distanceOutput = addRuns(automatonRunthrough[0], units, unitLengths);
	var modifiedStringAfterDistanceCalculation = formatString(escapedEntry, units);
	var userAutomatonOutput = userAutomaton(modifiedStringAfterDistanceCalculation);
	if (automatonRunthrough[1].length > 0) {
		$("#id_distance")[0].value = distanceOutput;
	}
	var mceInstance = tinymce.get("tinyMCEEntry");
	mceInstance.setContent(replaceNewlinesWithParas(userAutomatonOutput), { format: 'raw'});
	// CURSOR REPOSITIONING FROM http://stackoverflow.com/questions/1253303/whats-the-best-way-to-set-cursor-caret-position
	var cursorSpan = mceInstance.dom.select("span#lastCursor");
	mceInstance.selection.select(cursorSpan[0]);
	mceInstance.selection.collapse();
	mceInstance.dom.remove("lastCursor");
}

// FROM http://stackoverflow.com/questions/6234773/can-i-escape-html-special-chars-in-javascript
function escapeHTML(text) {
	return text.replace(/&/g, "&amp;")
				.replace(/</g, "&lt;")
				.replace(/>/g, "&gt;")
				.replace(/"/g, "&quot;")
				.replace(/'/g, "&#039;");
}

function userAutomaton(entry) {
	var workingState = 0;
	var outputString = "";
	var numbers = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"];
	var letters = ["a", "A", "b", "B", "c", "C", "d", "D", "e", "E", "f", "F", "g", "G", "h", "H", "i", "I", "j", "J", "k", "K", "l", "L", "m", "M", "n", "N", "o", "O", "p", "P", "q", "Q", "r", "R", "s", "S", "t", "T", "u", "U", "v", "V", "w", "W", "x", "X", "y", "Y", "z", "Z"];
	var currentUser = "";
	while (entry.length > 0) {
		if (workingState == 0) {
			if (entry[0] == "@") {
				workingState = 1;
				outputString = outputString + "@";
				entry = entry.slice(1, entry.length);
			} else {
				workingState = 0;
				outputString = outputString + entry[0];
				entry = entry.slice(1, entry.length);
			};
		} else {
			if (numbers.indexOf(entry[0]) >= 0 || letters.indexOf(entry[0]) >= 0 || entry[0] == "_") {
				currentUser = currentUser + entry[0];
				workingState = 1;
				entry = entry.slice(1, entry.length);
			} else {
				if (currentUser.length > 0) {
					outputString = outputString + "<a href=\"/" + currentUser + "\">" + currentUser + "</a>" + entry[0];
				} else {
					outputString += entry[0];
				}
				workingState = 0;
				entry = entry.slice(1, entry.length);
				currentUser = "";
			};
		};
	};
	
	if (currentUser.length > 0) {
		outputString = outputString + "<a href=\"/" + currentUser + "\">" + currentUser + "</a>";
	};
	
	return outputString;
		
	
}

rogging/templates/rogging/loggerjspostload.html
function adjustCSS() {
	if ($(window).width() < 768) {
		$("#id_date").css("width", "100%").css("display", "block");
		$("#id_distance").css("width", "100%").css("display", "block");
		$("#id_timeRan").css("width", "100%").css("display", "block");
		$("#id_shoe").css("width", "100%").css("display", "block");
		$("#id_type").css("width", "100%").css("display", "block");
		$("#id_subtype").css("width", "100%").css("display", "block");
	} else {
		$("#id_date").css("width", "33.33%").css("display", "inline");
		$("#id_distance").css("width", "33.33%").css("display", "inline");
		$("#id_timeRan").css("width", "33.33%").css("display", "inline");
		$("#id_shoe").css("width", "33.33%").css("display", "inline");
		$("#id_type").css("width", "33.33%").css("display", "inline");
		$("#id_subtype").css("width", "33.33%").css("display", "inline");
	};
};

var shoe = $("#id_shoe");
var type = $("#id_type");
var subtype = $("#id_subtype");
shoe.addClass("formComponent").addClass("dateanddistance").addClass("formSelectComponent");
type.addClass("formComponent").addClass("dateanddistance").addClass("formSelectComponent");
subtype.addClass("formComponent").addClass("dateanddistance").addClass("formSelectComponent");
window.addEventListener("resize", adjustCSS);
adjustCSS();

rogging/templates/rogging/logoutsuccess.html
{% extends "rogging/starter.html" %}

{% block content %}
Logout successful.
{% endblock %}

rogging/templates/rogging/passwordresetsent.html
{% extends 'rogging/starter.html' %}

{% block content %}
<div>
	A password reset email has been sent to the email account associated with the account you specified. Please check your email.
</div>
{% endblock %}

rogging/templates/rogging/predelete.html
		{{ form.shoe }}{{ form.shoe.errors }}
		{{ form.type }}{{ form.type.errors }}
		{{ form.subtype }}{{ form.subtype.errors }}
		<div class="previewBackground">
			<img class="previewWellHeaderImage" src="{{ STATIC_URL }}curlyquote.png"></img>
		</div>
		<div id="tinyMCEEntry" oninput=""></div>
		<textarea id="id_entry" name="entry" hidden></textarea>

rogging/templates/rogging/searchresults.html
{% for result in results %}
<div class="result">
	<a href="{% url 'rogging:show' username=result.username %}">
		<div>	
			<img src="{{ result.roggeelog.getThumbnail }}" class="resultThumb"/>
			<div>
				{% if result.roggeelog.name != None and result.roggeelog.name != "" %}
				<div>
					{{ result.roggeelog.name }}
				</div>
				{% endif %}
				<div>
					@{{ result.username }}
				</div>
			</div>
		</div>
	</a>
</div>
{% endfor %}

rogging/templates/rogging/usernamesrequestemailnousernames.html
<!-- body tag insertion and inline style suggestion from http://www.sitepoint.com/how-to-code-html-email-newsletters/ -->
<html>
	<body>
		<div>
			<div id="title" style="font-family:'Brush Script MT', sans-serif; font-size:30px; background:#202020; color:#fff; text-align:center; padding-bottom:7px;">
				rogger
			</div>
			<div id="content" style="font-family:sans-serif; font-weight:lighter; background-color:#fff;">
				<div id="greeting" style="padding-top:10px; text-align:center;">Hi!</div>
				<div class="paddingDiv" style="padding:10px;"> 
					<div class="paddingTopDiv" style="padding-top:10px;">
						No usernames on Rogger are associated with your email account ({{ email }}). Contact ben@rogger.co if you notice any problems regarding this issue.
					</div>
					<div class="paddingTopDiv" style="padding-top:10px;">
						Thanks!
						<br>- Rogger team
					</div>
				</div>
			</div>
		</div>
	</body>
</html>